version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  default:
    external: false

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      # - alertmanager:alertmanager
    networks:
      - default
    deploy:
      mode: global

#  node-exporter:
#    container_name: node-exporter
#    image: prom/node-exporter
#    volumes:
#      - /proc:/host/proc
#      - /sys:/host/sys
#      - /:/rootfs
#    command:
#      - '-collector.procfs=/host/proc'
#      - '-collector.sysfs=/host/sysfs'
#      - '-collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
#    expose:
#      - 9100
#    networks:
#      - back-tier
#  alertmanager:
#    image: prom/alertmanager
#    ports:
#      - 9093:9093
#    volumes:
#      - ./alertmanager/:/etc/alertmanager/
#    networks:
#      - back-tier
#    command:
#      - '-config.file=/etc/alertmanager/config.yml'
#      - '-storage.path=/alertmanager'

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - default
    deploy:
      mode: global

#  grafana:
#    image: grafana/grafana:4.3.2
#    depends_on:
#      - prometheus
#    ports:
#      - 34219:34219
#    volumes:
#      - grafana_data:/var/lib/grafana
      #- ./conf/grafana.ini:/etc/grafana/grafana.ini
#    env_file:
#      - config.monitoring
    # networks:
    #   - front-tier
    #   - back-tier

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/conf.d/proxy.conf

  # caddy:
  #   image: abiosoft/caddy:latest
  #   restart: always
  #   #command: --log stdout --conf /etc/Caddyfile --http2=false
  #   volumes:
  #     - ./Caddyfile:/etc/Caddyfile
  #   ports:
  #     - 80:80
